const quotes = [
  // effort & work
  "the hardest part is starting. after that it's just not stopping.",
  "you can want it or you can work for it. most people just want it.",
  "nobody is going to hand you the life you want. that was never the deal.",
  "consistency beats talent when talent doesn't show up consistently.",
  "the days you don't feel like it are the days that count the most.",
  "discipline is just doing the thing even when the motivation's gone.",
  "the grind isn't fun. that's why most people quit. that's also why you shouldn't.",
  "small effort every day beats massive effort every now and then.",
  "if you can't be bothered to practice when no one's watching, don't be surprised when it shows.",
  "put in reps. results are just reps that finally showed up.",
  "the difference between where you are and where you want to be is work. just work.",
  "stop waiting to feel ready. ready is a myth.",
  "your future self is being built by what you do today. act accordingly.",
  "average effort produces average results. that's not judgment — that's math.",
  "you don't have to be the most talented person in the room. you just have to be the most consistent.",
  "outwork your excuses.",
  "the work you do when you're tired is the work that builds character.",
  "inspiration is for amateurs. pros just show up.",
  "nobody is born skilled. skilled is just what practice looks like from the outside.",
  "one hour a day on the thing you care about changes everything over time.",
  "the gap between who you are and who you want to be is called work.",
  "half the battle is just showing up when you don't feel like it.",
  "do the thing badly at first. do it badly until you do it well.",
  "momentum is a choice. so is staying still.",
  "what you do every day matters more than what you do once in a while.",
  "a year of consistent effort looks like overnight success from the outside.",
  "no shortcuts exist to the places worth going.",
  "effort compounds. so does coasting.",
  "show up. do the work. go home. repeat until results.",
  "the person who practices is always beating the person who plans to practice.",

  // failure & setbacks
  "failing doesn't make you a failure. quitting before you try again does.",
  "every L is a lesson if you're willing to sit with it long enough.",
  "you're allowed to fail. you're not allowed to use it as a reason to stop.",
  "the worst outcome is usually not as bad as the fear of it.",
  "the only person keeping a detailed record of your failures is you.",
  "failing at something means you tried. most people never even get there.",
  "everyone who is good at something failed at it first. usually a lot.",
  "embarrassment is temporary. giving up is permanent.",
  "the comeback is always more interesting than the story without the setback.",
  "a loss is only a waste if you learn nothing from it.",
  "people don't remember how many times you fell. they remember if you got back up.",
  "failure is expensive but it's also the tuition for the version of you that knows better.",
  "the thing that broke you is usually the thing that built you.",
  "nobody tells you this: the people you admire failed repeatedly before they were admirable.",
  "you haven't failed until you've decided to stop trying.",
  "your biggest setback is just your most dramatic turning point.",
  "a bad day doesn't mean a bad life. don't make permanent decisions from temporary situations.",
  "the rough patches aren't the exception. they're part of the deal.",
  "whatever knocked you down has no say in whether you stay down.",
  "losing one battle isn't losing the war unless you let it be.",
  "the comeback requires you to actually come back.",
  "everybody has a plan until things get hard. the ones who make it revise and keep going.",
  "pain is temporary but what you build through it can last.",
  "you've survived 100% of your worst days so far.",
  "your lowest points are not your ending points.",
  "what you survive often becomes what you're best at.",

  // people & relationships
  "not everyone who smiles at you is for you.",
  "the people who love you will show it. you won't have to guess.",
  "never beg someone to choose you. if they can't see it, let them miss it.",
  "you'll outgrow people. that's not sad. that's growth.",
  "whoever makes you feel like you're too much to handle isn't enough for you.",
  "the red flags you ignored in the beginning don't become green flags later.",
  "someone who genuinely wants to be in your life will make it clear. no confusion.",
  "you deserve people who choose you. not people who keep you as an option.",
  "not everyone you lose is a loss.",
  "the energy people bring says more about them than it says about you.",
  "some people leave your life and you only realize later it was a gift.",
  "people show you who they are in small moments. pay attention.",
  "if you have to convince someone to treat you well, you've already answered your own question.",
  "protect your peace more than you protect your relationships.",
  "a real one will never make you question if they're real.",
  "you can love someone and still know they're not right for you.",
  "the connection you're forcing is not the connection you need.",
  "surround yourself with people who make you want to be better without making you feel worse.",
  "not everyone who's nice to you is your friend.",
  "the people who leave your life aren't always the ones who lost.",
  "loyalty isn't just not betraying people. it's showing up when it's inconvenient.",
  "your circle should challenge you not just agree with you.",
  "be careful who you vent to. some people collect your secrets like ammunition.",
  "the energy of the five people you spend most time with is the energy you become.",
  "how you treat people who can do nothing for you says everything about you.",

  // love & heartbreak
  "heartbreak is just love with nowhere to go. give it time.",
  "you're allowed to be sad about it. you're not allowed to make it your whole identity.",
  "missing someone doesn't mean going back to them was ever the right move.",
  "the love that hurt you the most was also the one that taught you the most.",
  "you can't love someone into loving you back. that's not love — that's negotiation.",
  "sometimes you have to let someone go to find out they were never yours to keep.",
  "the right person won't make you feel like loving them is a full-time job.",
  "stop texting first if you're always texting first.",
  "you deserve someone who's excited about you. not just comfortable with you.",
  "love should add to your life. not drain it.",
  "being alone is better than being with someone who makes you feel alone.",
  "chasing someone who's walking away just makes you tired.",
  "if they wanted to, they would. that's the whole explanation.",
  "not all love stories are meant to last forever. some are just meant to teach you.",
  "a relationship that requires you to be less yourself isn't a relationship — it's a cage.",
  "heal before you repeat.",
  "you can't fix someone who doesn't think they're broken.",
  "the best thing you can do after heartbreak is build something you're proud of.",
  "when it's right, you won't need to convince yourself it is.",
  "the version of them you fell for and the version that actually exists are often two different people.",
  "someone who keeps you guessing about how they feel is answering your question.",

  // self-worth
  "stop apologizing for who you are to people who'd never apologize for who they are.",
  "your value doesn't drop because someone failed to see it.",
  "you're not for everyone. neither is anyone worth having.",
  "the moment you stop needing approval is the moment your life starts working.",
  "what other people think of you is none of your business.",
  "confidence isn't walking into a room thinking everyone loves you. it's not caring either way.",
  "you can't be everyone's favorite and also be fully yourself.",
  "you don't need to earn your own respect.",
  "who you are when no one's watching is who you actually are.",
  "stop shrinking to fit spaces that were never meant for you.",
  "your worth isn't measured by productivity, output, or how much you do for others.",
  "being yourself will make some people uncomfortable. that's their problem.",
  "the opinion of someone you wouldn't take advice from shouldn't affect your day.",
  "quiet confidence hits different than loud insecurity.",
  "stop comparing your beginning to someone else's middle.",
  "you're allowed to take up space. all of it.",
  "the things you're embarrassed about are usually the things that make you interesting.",
  "define yourself before someone else does.",
  "who you are is enough. work on getting more comfortable with that.",
  "you don't need to earn the right to exist comfortably in your own skin.",
  "your self-image is the lens through which you see everything. clean it.",

  // mindset
  "the way you talk to yourself becomes the way you talk to the world.",
  "you can do it scared. scared and doing it still counts.",
  "doubt is normal. letting doubt be in charge is a choice.",
  "the bravest thing you can do is try something you might fail at in front of people.",
  "most of the things you worry about never happen.",
  "your mindset is the only thing that's 100% in your control.",
  "what you focus on expands. choose carefully.",
  "gratitude isn't soft. it's strategic.",
  "perspective is free and it can change everything.",
  "the story you tell yourself about your life becomes your life.",
  "optimism isn't naive. it's a choice you make with full knowledge of the alternatives.",
  "the version of you that wins is the one who believes winning is possible.",
  "your thoughts are not facts. treat them accordingly.",
  "the ceiling of your ambition is set by what you believe you deserve.",
  "calm is a superpower. develop it.",
  "you don't have to feel motivated. you just have to move.",
  "anxiety is a liar. treat it like one.",
  "your biggest competition is yesterday's version of you.",
  "a bad day is just a bad day. don't let it become a bad story.",
  "how you respond to what happens to you is always your choice.",
  "the narrative in your head has more power than any external circumstance.",
  "bitterness is just anger with nowhere to go. find somewhere for it to go.",
  "being unbothered is a skill worth developing.",

  // time & priorities
  "a year from now you'll either be closer to where you want to be or further. same amount of time either way.",
  "how you spend your days is how you spend your life.",
  "time is the one thing you can't get back. spend it like it.",
  "your priorities are what you actually do, not what you say you'll do.",
  "the time you spend complaining could be spent changing things.",
  "the best time to start was yesterday. the second best time is now.",
  "wasted time is the most expensive thing most people buy.",
  "if you don't make time for the things that matter, they'll stop mattering.",
  "stop saying you'll do it later. later has a terrible track record.",
  "be protective of your time. most people are generous with yours and cheap with their own.",
  "you don't find time. you make time. for the things that matter, you just make it.",
  "be where you are. the future will get here without you obsessing over it.",
  "invest your time in things that compound — knowledge, relationships, health.",
  "show up now and worry about the rest later.",
  "the person who starts today is always ahead of the person who waits for perfect.",
  "urgency about the wrong things is just time stolen from the right ones.",
  "the seasons pass whether you use them or not.",

  // money & success
  "money isn't everything but being broke affects everything.",
  "building wealth is boring. that's exactly why most people don't.",
  "spend less than you make. invest the difference. do that for decades.",
  "the best investment you'll ever make is in your own skills.",
  "work hard enough to have options. options are freedom.",
  "don't buy things to impress people you don't actually like.",
  "success isn't one moment. it's a thousand small decisions over a long time.",
  "what looks like overnight success from the outside is usually ten years of work on the inside.",
  "don't confuse busy with productive. one makes you feel better. the other actually moves things.",
  "build income you don't have to trade every hour for. that's the long game.",
  "nobody gets rich off one good year. they get rich off consistent good habits.",
  "pay yourself first. even a small amount. the habit matters more than the number.",
  "your network is your net worth is cliché because it's true.",
  "ambition without a plan is just daydreaming.",
  "the shortcuts to success are usually shortcuts to failure.",
  "want less and you're rich. most people never figure this out.",
  "the people at the top of most fields got there by being reliably good, not occasionally brilliant.",
  "broke is a temporary situation. thinking like a broke person is a mindset.",

  // health & habits
  "your body is the one thing you'll have your entire life. treat it accordingly.",
  "sleep is not laziness. it's maintenance.",
  "you can't pour from an empty cup. take care of yourself so you can take care of things.",
  "the habits you build now are the health you have in 20 years.",
  "movement is medicine. it doesn't have to be a gym. just move.",
  "your energy is your most valuable resource. protect it.",
  "the person who sleeps 8 hours and does 6 focused hours beats the person who sleeps 5 and grinds 14.",
  "your mental health is not a luxury. it's the foundation.",
  "stress that doesn't get processed stays in the body. find a way to process it.",
  "the thing you're using to cope might be the thing keeping you stuck.",
  "you can't outwork a bad lifestyle.",
  "taking care of yourself isn't selfish. falling apart helps nobody.",
  "most things in your life get better when you consistently sleep, move, and eat well.",
  "bad habits are expensive. good habits compound.",
  "addiction and habit look similar from the outside. the difference is who's in control.",

  // growing up & life
  "nobody has it all figured out. not the people who look like they do. not even close.",
  "adulting is mostly just doing hard things before you feel ready.",
  "some lessons you can only learn by living through them. there's no shortcut.",
  "the version of you that makes it is just the version that kept going.",
  "life isn't supposed to feel stable all the time. stability is something you build, not something you're given.",
  "being uncomfortable is not a sign you're doing something wrong. it's usually a sign you're growing.",
  "the world doesn't owe you anything. but it also doesn't have it out for you. make your move.",
  "the chapter you're in right now will make sense later.",
  "you don't need to have your whole life planned. you just need your next right move.",
  "most adults are just older versions of confused kids. everyone is figuring it out.",
  "your parents were just people too. they were figuring it out same as you.",
  "the experiences that break your heart open a little are also the ones that expand your capacity for joy.",
  "you'll look back on this period and be grateful you didn't quit.",
  "the middle of the journey always looks like failure. keep going.",
  "grow at your own pace. seasons have timing that can't be rushed.",

  // dealing with people
  "pick your battles. you can't fight everything and win anything.",
  "the loudest person in the room usually has the least to say.",
  "you can be right and lose the argument at the same time. choose the win that matters.",
  "people who talk about others constantly when they're not around will talk about you too.",
  "you can't control how people treat you. you can control how long you let it continue.",
  "hard conversations save you from harder ones later.",
  "give people the benefit of the doubt until they show you they don't deserve it.",
  "you can disagree with someone without making them the enemy.",
  "some people argue to win. some argue to understand. figure out which you're dealing with.",
  "not every argument needs your participation.",
  "ignore the advice of people who haven't done the thing they're advising you on.",
  "most people are doing the best they can with what they have. that doesn't make bad behavior okay. it just explains it.",
  "don't take it personally. it's almost never about you.",
  "drama is a choice. you can opt out.",
  "be the kind of person in the room who makes others feel like they belong.",

  // clarity & purpose
  "knowing what you want is harder than knowing how to get it. start there.",
  "purpose isn't something you find. it's something you build through action.",
  "clarity comes from doing, not from thinking about doing.",
  "if you don't know where you're going, any road gets you there.",
  "the goals that matter to you should scare you at least a little.",
  "stop making decisions based on who you are now. make them based on who you're becoming.",
  "your why has to be bigger than your excuses.",
  "knowing yourself is the work of a lifetime but starting early helps.",
  "you won't always love what you do. love why you do it.",
  "direction matters more than speed. fast in the wrong direction is just faster to the wrong place.",
  "the clearer you are about what you want, the less other people's opinions matter.",
  "do the thing you keep putting off. it's not going to get easier.",
  "not knowing what you want is fine. moving anyway is the solution.",
  "the life you want is on the other side of the decisions you keep avoiding.",

  // ego & humility
  "the smartest people in the room are usually the ones listening.",
  "the moment you think you have nothing left to learn is the moment you stop growing.",
  "ego is the enemy of growth. stay humble when things are going well.",
  "there's always someone who knows more than you. find them and ask questions.",
  "the most successful people are usually the least interested in looking successful.",
  "being teachable is a superpower that most people throw away as soon as they get a little success.",
  "wrong about something? admit it quickly and move on. it costs less than defending it.",
  "being the least experienced person in the right room is better than being the expert in the wrong one.",
  "humility isn't weakness. it's just knowing you're still learning.",
  "the way you treat people who can do nothing for you tells everyone above you who you really are.",

  // discipline
  "motivation is the spark. discipline is the engine.",
  "you won't always want to do the work. do it anyway — the motivation usually shows up after.",
  "routine is the skeleton of ambition.",
  "the best athletes in the world still practice the basics. there's a reason.",
  "discipline is self-respect in action.",
  "you can't motivate yourself into discipline. you discipline yourself until motivation becomes irrelevant.",
  "freedom comes from discipline, not from avoiding it.",
  "systems outlast motivation every time.",
  "the morning routine isn't magic. showing up consistently is the magic.",
  "do it until it's automatic. then do the next hard thing.",

  // learning & growth
  "read more than average. your knowledge compounds.",
  "the best students in life never stop being students.",
  "curiosity is worth protecting. don't let the grind kill it.",
  "you learn more from a hard year than from an easy decade.",
  "the person who reads seriously for ten years becomes someone different.",
  "fail fast and learn what the failure is teaching you.",
  "knowledge is useless until it becomes behavior.",
  "growth is uncomfortable almost by definition. get okay with that.",
  "being willing to look stupid while you're learning is how you eventually look smart.",
  "every expert was once a beginner who didn't quit.",

  // fear
  "fear is information, not instruction.",
  "the thing you're most afraid of is usually the thing you most need to do.",
  "you can feel fear and still make the move. that's called courage.",
  "running from fear makes it bigger. moving toward it makes it smaller.",
  "the worst case scenario you're imagining is almost never as bad as the freeze it causes.",
  "courage isn't the absence of fear. it's action in the presence of it.",
  "being afraid means something matters to you. that's not weakness. that's care.",
  "the fear before the thing is almost always worse than the thing.",
  "do the scary thing and watch it become the thing you're good at.",
  "you won't outthink fear. you have to outwalk it.",

  // change
  "if you keep doing what you're doing, you'll keep getting what you're getting.",
  "the hardest change is the one that requires giving up who you've been.",
  "you can change your life. it just requires changing your days first.",
  "the person you want to be and the person you are is just a series of habits apart.",
  "resistance to change is just fear wearing different clothes.",
  "what worked for the old version of you might not work for who you're becoming.",
  "change is uncomfortable right up until the moment it becomes necessary.",
  "if you're not growing, you're declining. there's no stable.",
  "the environment you're in shapes you more than most things. choose it carefully.",

  // forgiveness
  "forgiveness isn't for them. it's for you.",
  "holding a grudge is like drinking poison and waiting for the other person to die.",
  "letting go isn't the same as saying it was okay.",
  "the weight of resentment is always heaviest on the person carrying it.",
  "you can forgive someone and still never speak to them again.",
  "bitterness keeps you stuck in a moment that already passed.",
  "release what happened. you can't build something new while holding the old thing.",

  // social media & comparison
  "social media is a highlight reel. stop comparing your full life to someone else's best moments.",
  "the more time you spend watching other people's lives, the less time you spend building your own.",
  "your real life doesn't need online validation to count.",
  "the person who looks like they have it all together online usually doesn't offline.",
  "stop performing for the algorithm. perform for the life you actually want.",
  "comparison is the thief of joy and social media is the dealer.",
  "the likes don't translate to the things that actually matter.",
  "if you deleted social media for a month, most of your comparison anxiety would disappear too.",

  // solitude & peace
  "learn to enjoy your own company. you'll have it your whole life.",
  "peace is an inside job. stop looking for it outside.",
  "not every moment needs to be filled. silence is useful.",
  "being alone and being lonely are completely different things.",
  "your best thinking usually happens in the quiet.",
  "protecting your peace is not antisocial. it's strategic.",
  "some of your best ideas are hiding behind constant distraction.",
  "you don't need to be in contact with everyone all the time. it's okay to disappear for a bit.",

  // gratitude
  "someone right now would trade everything to have your problems.",
  "you can want more and still be grateful for what you have. both at once.",
  "the things you take for granted are the things someone else is praying for.",
  "gratitude turns what you have into enough, at least for now.",
  "slow down enough to notice what's already working in your life.",
  "the people around you that you overlook are the ones you'll miss most.",
  "what you appreciate appreciates.",

  // honesty & communication
  "being honest is almost always the harder choice and almost always the right one.",
  "what you can't say is controlling you.",
  "the conversation you keep avoiding is the one you need most.",
  "clear is kind. vague is cruel.",
  "say the hard thing once clearly instead of the easy thing a hundred times unclearly.",
  "a hard conversation handled well beats years of quiet resentment.",
  "mean what you say. it costs nothing and builds everything.",
  "the best relationships are the ones where you can say anything.",

  // resilience
  "strength isn't never breaking down. it's being willing to build back up.",
  "the storm you're in is also the storm you're learning to navigate.",
  "it's okay to be a mess. it's not okay to stay one indefinitely.",
  "what you survive often becomes what you're most capable of.",
  "the rough version of you is still a version worth fighting for.",
  "you've been through worse and you made it. this is no different.",
  "a bad season doesn't mean a bad life.",
  "there's always a way through. not always a way around.",
  "when life gets heavy, get stronger. no other option.",
  "the people who've been through the most are usually the ones who understand the most.",

  // authenticity
  "being yourself costs less energy than performing a version of yourself for others.",
  "pretending to be okay when you're not is its own kind of exhausting.",
  "there's no version of success worth having that requires you to stop being yourself.",
  "the most interesting people aren't trying to be interesting.",
  "your weirdness is not a bug. it's the feature.",
  "authentic beats polished every time for the people who actually matter.",
  "you don't need to be likable to everyone. you need to be real to the right ones.",
  "stop editing yourself in real time to manage how you're being perceived.",

  // decisions
  "not making a decision is also a decision.",
  "make the decision with the information you have. don't wait for certainty that won't come.",
  "future you will handle what present you is afraid of.",
  "every good decision starts with being honest about what you actually want.",
  "choose discomfort now to avoid regret later.",
  "the decision that scares and excites you simultaneously is usually the right one.",
  "be decisive. wrong direction you can correct. no direction, you can't.",
  "the hardest decisions are the ones where both options are real. decide anyway.",
  "stop overthinking and start. the clarity usually comes after the movement, not before.",

  // misc wisdom
  "everything changes. prepare for that and then stop being surprised by it.",
  "the truth is almost always simpler than the story you make up about it.",
  "be the kind of person you'd want to know.",
  "do what you say you're going to do. it's the rarest form of integrity.",
  "the best version of yourself isn't a destination. it's a direction.",
  "learning to sit with uncertainty is one of the most important things you can develop.",
  "be honest with yourself first. everything else flows from there.",
  "stop performing your life and start living it.",
  "the good stuff doesn't happen in your comfort zone.",
  "nobody who played it completely safe ever did anything remarkable.",
  "regret for the things you didn't try is worse than regret for the things you did.",
  "help people when you can. it comes back.",
  "you are not your past. you are what you do now.",
  "go outside. drink water. get enough sleep. most problems look different after that.",
  "nobody is saving you. you are saving yourself. and that's more than fine.",
  "you can be a work in progress and still be worth something right now.",
  "measure yourself by your own standards, not by someone else's finish line.",
  "every person you meet is carrying something you can't see. act accordingly.",
  "sometimes the most productive thing you can do is rest.",
  "ask for help. it's not weakness. it's efficiency.",
  "be okay with uncertainty. it's the foundation of actually living.",
  "make peace with the fact that you can't control outcomes — only what you put in.",
  "a good attitude about a bad situation is the most underrated skill there is.",
  "the universe isn't conspiring against you. it's indifferent. that means you have full say.",
  "do the reps. results are just reps that finally showed up.",
  "care about the right things.",
  "less talk. more do.",
  "earn the confidence, don't just claim it.",
  "be the kind of person you'd trust.",
  "your circle should push you, not just validate you.",
  "the answer is almost always more action, not more planning.",
  "say what you mean. mean what you say.",
  "choose the hard path early so the easy path appears later.",
  "comparison is a trap with no exit.",
  "be someone your younger self would look up to.",
  "fix the problem, not the blame.",

  // more on people
  "the people who mind don't matter and the people who matter don't mind.",
  "protect your energy like you protect your time.",
  "someone who drains you every time you see them is not a friend. they're a cost.",
  "don't shrink yourself to make insecure people comfortable.",
  "the people closest to you have the most access to you. choose carefully.",
  "let people miss you sometimes. it reveals a lot.",
  "never make someone a priority who only makes you an option.",
  "match energy. don't donate it.",

  // more on work & purpose
  "the work matters. but so does knowing why you're doing it.",
  "passion fades but discipline is permanent. don't rely on passion alone.",
  "find the thing you'd be okay doing badly for a while because you love it enough. then get good.",
  "a job that pays you isn't always a career that fulfills you. know the difference.",
  "money is a tool. knowing what you're building is the point.",
  "the grind that has no purpose just grinds you down.",
  "be the person who finishes what they start.",
  "excellence isn't perfection. it's consistent above-average effort over time.",
  "the best players aren't always the most naturally gifted. they're the ones who stayed.",

  // more on identity
  "your past doesn't define you but it does inform you. learn from it, don't live in it.",
  "you're allowed to evolve. who you were last year doesn't have to run your life now.",
  "identity is built by the small choices you make every day, not the big moments.",
  "you get to decide who you are. don't let circumstances make that decision for you.",
  "the version of you that wins is just the current version plus time and intention.",
  "becoming is a process, not an event.",
  "don't let your worst days give you your most permanent opinions about yourself.",

  // more on life
  "the things that matter most rarely make the most noise.",
  "the older you get the more you realize how much you don't know.",
  "simple is usually smarter. complexity is often just noise.",
  "you can't fast forward to the good part. you have to live the whole thing.",
  "the small joys are the ones that actually add up to something.",
  "stop saving the good stuff for later. use it now.",
  "most people overestimate what they can do in a year and underestimate what they can do in five.",
  "the life you live quietly is worth more than the life you perform loudly.",
  "connection is what makes the whole thing worth it.",
  "be in the room with the people you love. actually be there.",
  "experiences age better than things.",
  "the memories you're not making yet are the ones you'll want most.",

  // closing punchy ones
  "start before you're ready.",
  "slow down to go faster.",
  "earn your opinion by living with the consequences of it.",
  "do it badly first. do it better after.",
  "don't wait for permission.",
  "the answer is usually simpler than you want it to be.",
  "if it's important, it goes first. everything else works around it.",
  "keep going. that's the whole secret.",
];
